name: CIS
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools
  - bwa>=0.7.17
#  - mamba
  - fastp
  - imagemagick
  - jinja2
  - kraken2
  - networkx
  - pip
  - python>=3.8
  - qualimap
  - r-base==4.1
  - r-rlang>=1.0.2
  - r-ggplot2
  - r-seqinr
  - r-stringr
  - r-optparse
  - r-data.table
  - r-dplyr
  - r-ggpubr
  - htslib==1.13
  - samtools==1.13
  - bcftools==1.13
  - snpeff
  - seqmagick
  - snakemake-minimal>=5.13
  - snpEff
  - singularity==3.7.1
  - pip:
    - pandas
    - pango-collapse
    - psutil
    - pygraphviz
    - cmp_version
prefix: /home/cfos/miniconda3/envs/CIS
